Important bug fixes for all scripts

diff --git a/ausmt/ausmt-cleanup b/ausmt/ausmt-cleanup
--- a/ausmt/ausmt-cleanup
+++ b/ausmt/ausmt-cleanup
@@ -129,8 +129,7 @@ echo "Emergency AUSMT Recovery $(date)" >> ${PATCH_LOG_FILE}
 echo "------------------------------------------------------" >> ${PATCH_LOG_FILE}
 
 if [ -z "${IPKG_OFFLINE_ROOT}" ]; then
-  echo "ERROR: IPKG_OFFLINE_ROOT must be supplied to the postinst" | tee -a ${PATCH_LOG_FILE} 1>&2
-
+  echo "ERROR: IPKG_OFFLINE_ROOT must be supplied for the cleanup" | tee -a ${PATCH_LOG_FILE} 1>&2
   exit 1
 fi
 
@@ -216,7 +215,7 @@ if [ -e ${PATCH_CONTROL_DIR}/file_list ]; then
     echo "Checking file: ${file}" >> ${PATCH_LOG_FILE}
     echo "  version: ${version}" >> ${PATCH_LOG_FILE}
 
-    if [ -f ${bck_file} ]; then
+    if [ -f ${bck_file} ] && [ -f ${file} ]; then
       find_palm_md5sum
 
       file_md5sum=`md5sum ${file} | awk '{print $1}'`
@@ -256,9 +255,19 @@ if [ -e ${PATCH_CONTROL_DIR}/file_list ]; then
         fi
       fi
     else
-      echo | tee -a ${PATCH_LOG_FILE} 1>&2
-      echo "WARNING: Could not find backup file!" | tee -a ${PATCH_LOG_FILE} 1>&2
-      echo | tee -a ${PATCH_LOG_FILE} 1>&2
+      if [ -f ${bck_file} ]; then
+        echo "Removing backup file..." | tee -a ${PATCH_LOG_FILE}
+
+        rm -f ${bck_file}
+      else
+        echo | tee -a ${PATCH_LOG_FILE} 1>&2
+        echo "WARNING: Could not find backup file!" | tee -a ${PATCH_LOG_FILE} 1>&2
+        echo | tee -a ${PATCH_LOG_FILE} 1>&2
+      fi
+
+      if [ ! -f ${file} ]; then
+        echo "Unable to find original file, assuming OTA" >> ${PATCH_LOG_FILE}
+      fi
     fi
   done < ${PATCH_CONTROL_DIR}/file_list
 fi
